SELECT * FROM DOMA

ALTER TABLE KLADR
ALTER COLUMN NAME varchar(40) NOT NULL
ALTER TABLE KLADR
ALTER COLUMN CODE varchar(10) NOT NULL
GO
ALTER TABLE KLADR
ADD CONSTRAINT PK_KLADR PRIMARY KEY (NAME, CODE)
GO

ALTER TABLE SOCRBASE
ALTER COLUMN [LEVEL] varchar(5) NOT NULL
ALTER TABLE SOCRBASE
ALTER COLUMN SCNAME varchar(10) NOT NULL
GO
ALTER TABLE SOCRBASE
ADD CONSTRAINT PK_SOCRBASE PRIMARY KEY ([LEVEL], SCNAME)
GO

ALTER TABLE STREET
ALTER COLUMN NAME varchar(40) NOT NULL
ALTER TABLE STREET
ALTER COLUMN SOCR varchar(10) NOT NULL
ALTER TABLE STREET
ALTER COLUMN CODE varchar(17) NOT NULL
GO
ALTER TABLE STREET
ADD CONSTRAINT PK_STREET PRIMARY KEY (NAME, SOCR, CODE)
GO

ALTER TABLE ALTNAMES
ALTER COLUMN OLDCODE varchar(19) NOT NULL
ALTER TABLE ALTNAMES
ALTER COLUMN [LEVEL] varchar(1) NOT NULL
ALTER TABLE ALTNAMES
ALTER COLUMN NEWCODE varchar(19) NOT NULL
GO
ALTER TABLE ALTNAMES
ADD CONSTRAINT PK_ALTNAMES PRIMARY KEY (OLDCODE, NEWCODE, [LEVEL])

ALTER TABLE DOMA
ALTER COLUMN NAME varchar(40) NOT NULL
UPDATE DOMA
SET KORP = ''
WHERE KORP IS NULL
ALTER TABLE DOMA
ALTER COLUMN KORP varchar(10) NOT NULL
ALTER TABLE DOMA
ALTER COLUMN SOCR varchar(10) NOT NULL
ALTER TABLE DOMA
ALTER COLUMN CODE varchar(19) NOT NULL
GO
ALTER TABLE DOMA
ADD CONSTRAINT PK_DOMA PRIMARY KEY (NAME, KORP, SOCR, CODE)

CREATE TABLE USERS (
	Id int PRIMARY KEY,
	Username nvarchar(max),
	[Password] nvarchar(max),
	Fullname nvarchar(max)
)

ALTER TABLE USERS
ADD [Type] int


ALTER TABLE STREET
ADD SOCRNAME varchar(29)

UPDATE STREET
SET SOCRNAME = (SELECT TOP(1) SOCRNAME FROM SOCRBASE WHERE SOCR=SCNAME AND CAST(LEVEL AS int) > 3)

CREATE INDEX code_doma_index
ON DOMA(CODE)

SELECT * FROM USERS

ALTER TABLE USERS
ADD 
OblastCode varchar(max),
Oblast varchar(max),
RayonCode varchar(max),
Rayon varchar(max),
CityCode varchar(max),
City varchar(max),
StreetCode varchar(max),
Street varchar(max),
House varchar(max),
Flat varchar(max),
Village varchar(max),
VillageCode varchar(max)

ALTER TABLE USERS
ADD [Index] varchar(max)